spring.application.name=supervision-backend

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=supervision_db

server.port=8080

logging.level.org.springframework.data.mongodb=DEBUG

vmware.host=https://your-esxi-ip
vmware.username=your-username
vmware.password=your-password
vmware.enabled=false

proxmox.host=https://your-proxmox-ip:8006
proxmox.token=PVEAPIToken=user@pam!tokenid=your-secret-uuid
proxmox.enabled=false
proxmox.verify-ssl=false

sync.interval-ms=15000

auth.username=admin
auth.password=change-me
jwt.secret=change-this-to-a-long-random-secret-string
jwt.expiration-ms=86400000